# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b679a0f811611a37493b07e8f6640cdef3b0e801191f262eb3ca2f4c7f8081a115ed71f921e4c9a509bcff13c47d92568e14f355a76b5351a7d5dfd02052e952

test:
  secret_key_base: 72df71ee267f7861adb5667cd42594b9a5a5d4dfbfc32b3d724be2a520b35bfd2bbe08102c420577e1594c8b8ce24ff5f67c9159d8a96b3bb550771e37f495ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
